<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Insurance;

class InsuranceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Insurance::create([
            'description' => 'Property Insurance',
            'insurance_co' => 'ABC Insurance Co.',
            'contact_person' => 'John Doe',
            'phone' => '123-456-7890',
            'email' => 'john.doe@abcinsurance.com',
            'start_date' => '2024-01-01',
            'end_date' => '2024-12-31',
            'policy_no' => 'POL123456',
            'coverage' => 'Comprehensive',
            'limits' => '500,000',
            'deductible' => '5,000',
            'premium' => '2,000',
            'active' => '1',
            'delete' => '0',
        ]);

        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);

        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
        Insurance::create([
            'description' => 'Vehicle Insurance',
            'insurance_co' => 'XYZ Insurance Co.',
            'contact_person' => 'Jane Smith',
            'phone' => '987-654-3210',
            'email' => 'jane.smith@xyzinsurance.com',
            'start_date' => '2024-02-01',
            'end_date' => '2024-11-30',
            'policy_no' => 'POL654321',
            'coverage' => 'Third-Party Liability',
            'limits' => '100,000',
            'deductible' => '1,000',
            'premium' => '1,500',
            'active' => '1',
            'delete' => '0',
        ]);
    }
}
