<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TblAssetsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tbl_assets')->insert([
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Asset 1 Description',
                'assets_tag_id' => 'TAG123456',
                'purchase_date' => '2023-01-01',
                'cost' => 1000.00,
                'purchase_from' => 'Supplier 1',
                'brand' => 'Brand 1',
                'model' => 'Model 1',
                'serial_no' => 'SN123456',
                'site_id' => 1,
                'location_id' => 1,
                'category_id' => 1,
                'department_id' => 1,
                'asset_photo_file' => 'photo1.jpg',
                'depreciable_asset' => 1,
                'depreciable_cost' => 900.00,
                'salvage_value' => 100.00,
                'assets_life' => '5 years',
                'depreciation_method' => 'Straight Line',
                'date_acquired' => '2023-01-01',
                'funding_source' => 'Internal',
                'amount_debited' => 1000.00,
                'status_id' => 1,
                'delete' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Add more seed data as needed
        ]);
    }
}
